name: Deploy Arckenites

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Deploy application
        run: /opt/arckenites/deploy.sh
