import uuid
from pathlib import Path

from fastapi import HTTPException, UploadFile, status

# backend/app/core/uploads.py -> backend/uploads/support/
UPLOAD_ROOT = Path(__file__).resolve().parent.parent.parent / "uploads" / "support"

MAX_FILE_SIZE_BYTES = 10 * 1024 * 1024  # 10 MB
MAX_FILES_PER_MESSAGE = 3

# Allow-list, not a block-list — only these extensions/content-types are
# ever accepted, so an unexpected/dangerous type (e.g. an executable) is
# rejected by default rather than needing to be explicitly blocked.
ALLOWED_EXTENSIONS: dict[str, str] = {
    ".jpg": "image/jpeg",
    ".jpeg": "image/jpeg",
    ".png": "image/png",
    ".gif": "image/gif",
    ".webp": "image/webp",
    ".pdf": "application/pdf",
    ".doc": "application/msword",
    ".docx": "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
    ".txt": "text/plain",
}


def save_upload(file: UploadFile, contents: bytes) -> tuple[str, str, str, int]:
    """Validates and persists one uploaded file to local disk.

    Returns (storage_reference, file_name, file_type, file_size). The file
    is written under a random UUID name — the caller's original filename is
    kept only for display, never used to build a disk path, so a malicious
    filename (e.g. containing "../") can't escape the upload directory or
    collide with another file.
    """
    original_name = file.filename or "upload"
    ext = Path(original_name).suffix.lower()

    if ext not in ALLOWED_EXTENSIONS:
        allowed = ", ".join(sorted(ALLOWED_EXTENSIONS))
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail=f"File type not allowed. Accepted types: {allowed}",
        )

    if len(contents) > MAX_FILE_SIZE_BYTES:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail=f"File is too large. Maximum size is {MAX_FILE_SIZE_BYTES // (1024 * 1024)}MB.",
        )

    if not contents:
        raise HTTPException(status_code=status.HTTP_400_BAD_REQUEST, detail="Uploaded file is empty.")

    UPLOAD_ROOT.mkdir(parents=True, exist_ok=True)
    storage_reference = f"{uuid.uuid4().hex}{ext}"
    (UPLOAD_ROOT / storage_reference).write_bytes(contents)

    file_type = ALLOWED_EXTENSIONS[ext]
    return storage_reference, original_name[:255], file_type, len(contents)


def get_upload_path(storage_reference: str) -> Path:
    """Resolves a stored attachment's disk path. storage_reference is always
    a UUID + known extension generated by save_upload — never user input —
    so no path-traversal check is needed here, but resolve+require the
    upload root as a defensive boundary anyway."""
    path = (UPLOAD_ROOT / storage_reference).resolve()
    if UPLOAD_ROOT.resolve() not in path.parents:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Attachment not found")
    return path


def delete_upload(storage_reference: str) -> None:
    path = UPLOAD_ROOT / storage_reference
    if path.exists():
        path.unlink()
